language: java
sudo: required
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8
  - oraclejdk12

services:
  - postgresql

addons:
   hosts:
       - travis
   hostname: travis
   postgresql: "9.6"

before_script:
  - psql -c "CREATE USER ptcoretest WITH PASSWORD 'ptCoreTest101';"
  - psql -c 'create database ptcoretest;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE ptcoretest to ptcoretest;'
  - pip install --user codecov

script:
  - mvn -T 1C -B clean package jacoco:report

after_success:
  - codecov
  - mvn sonar:sonar -Dsonar.projectKey=javadev_pt-backend -Dsonar.organization=javadev-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN

