CREATE TABLE SHIPWRECK(
  ID BIGSERIAL NOT NULL,
  NAME VARCHAR(255),
  DESCRIPTION VARCHAR(2000),
  CONDITION VARCHAR(255),
  DEPTH INT,
  LATITUDE DECIMAL(9, 2),
  LONGITUDE DECIMAL(9, 2),
  YEAR_DISCOVERED INT
);
