ALTER TABLE ptcore.program ADD COLUMN file_name VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE ptcore.program ADD COLUMN file_size BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ptcore.program ADD COLUMN file_type VARCHAR(100) NOT NULL DEFAULT '';
