name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: ptcoretest
          POSTGRES_USER: ptcoretest
          POSTGRES_PASSWORD: ptCoreTest101
        ports:
          - 5432:5432
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: d16fc939fed96c332c7414ad93947e37ed44f1cc
      run: mvn -T 1C -B clean test jacoco:report org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.organization=javadev-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=javadev_pt-backend
    - uses: codecov/codecov-action@v4.3.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: target/site/jacoco/jacoco.xml
        name: codecov
        
